policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/aliengo/exported/policies/policy_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/aliengo/scene.xml"

# Total simulation time
simulation_duration: 120.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency
control_decimation: 4  # Adjusted for go2 based on dynamic response needs.

kps: [40, 40, 10000,  # FL (hip, thigh, calf)
      40, 40, 10000,  # FR (hip, thigh, calf)
      40, 40, 10000,  # RL (hip, thigh, calf)
      40, 40, 10000]  # RR (hip, thigh, calf)

kds: [1.0, 1.0, 200,  # FL (hip, thigh, calf)
      1.0, 1.0, 200,  # FR (hip, thigh, calf)
      1.0, 1.0, 200,  # RL (hip, thigh, calf)
      1.0, 1.0, 200]  # RR (hip, thigh, calf)

# kps: [20, 20, 20,  # FL (hip, thigh, calf)
#       20, 20, 20,  # FR (hip, thigh, calf)
#       20, 20, 20,  # RL (hip, thigh, calf)
#       20, 20, 20]  # RR (hip, thigh, calf)

# kds: [0.5, 0.5, 0.5,  # FL (hip, thigh, calf)
#       0.5, 0.5, 0.5,  # FR (hip, thigh, calf)
#       0.5, 0.5, 0.5,  # RL (hip, thigh, calf)
#       0.5, 0.5, 0.5]  # RR (hip, thigh, calf)


default_angles: [0.1, 0.8, -1.5,  # FL (hip, thigh, calf)
                -0.1, 0.8, -1.5,  # FR (hip, thigh, calf)
                 0.1, 1.0, -1.5,  # RL (hip, thigh, calf)
                -0.1, 1.0, -1.5]  # RR (hip, thigh, calf)

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12  # go2 has 12 actuated DOFs.
num_obs: 48  # Observations are scaled up for more sensors (IMU, joint state, etc.).

cmd_init: [0.5, 0, 0]
